### ISSUE TITLE
Automate pulling list of tickets

### ISSUE THREAD

**Issue by Cheukting** [EuroPython/discord#16]
We will pull the list of tickets from Pretix to a local store (csv for data base) in a certain time interval (e.g. 1 hour)

related to #3 - we need integration to Pretix to do that.

**Comment by NMertsch** [comment]
Since #108, all Pretix data is fetched on bot startup, and updated with recent changes every 5 minutes. Code:

- [Periodic fetch](https://github.com/EuroPython/discord/blob/04b36dcf9c226bddbf53eb510428b35c4ca039e5/EuroPythonBot/registration/cog.py#L175-L192)
- [Only fetch updates since last fetch](https://github.com/EuroPython/discord/blob/04b36dcf9c226bddbf53eb510428b35c4ca039e5/EuroPythonBot/registration/pretix_connector.py#L51)
